package application;

import javafx.fxml.FXML;
import javafx.animation.RotateTransition;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.util.Duration;

public class progressViewController {
	@FXML
	private ImageView img1;
	@FXML
	private ImageView img2;
	@FXML
	private ImageView img3;
	@FXML
	private ImageView img4;
	@FXML
	private Label Label1;
	@FXML
	private Label Label2;
	@FXML
	private Label Label3;
	@FXML
	private Label Label4;
	  private RotateTransition transition1,transition2,transition3,transition4;
	// Event Listener on Button.onAction
	@FXML
	public void loadAnimation(ActionEvent event) {
		// TODO Autogenerated

		img1.setImage(new Image("imag/synching.png"));
		Label1.setText("Checking For Update");
		transition1=new RotateTransition(Duration.seconds(5),img1);
		transition2=new RotateTransition(Duration.seconds(5),img2);
		transition3=new RotateTransition(Duration.seconds(5),img3);
		transition4=new RotateTransition(Duration.seconds(5),img4);
		RotateTransition[] transition={transition1,transition2,transition3,transition4};
			
		for(RotateTransition transitionIterator:transition){
			transitionIterator.setCycleCount(1);
			transitionIterator.setAutoReverse(false);
			transitionIterator.setRate(1);
			transitionIterator.setFromAngle(500);
			transitionIterator.setToAngle(2);
		}
		
		
		
		transition1.setOnFinished((ActionEvent event1)->{
			img1.setImage(new Image("imag/Ok-48.png"));
			Label1.setStyle("-fx-background-color:#47A563");
			img2.setImage(new Image("imag/synching.png"));
			Label1.setText("Here Text2");
			transition2.play();
			
		});
		transition1.play();
		
		
		transition2.setOnFinished((ActionEvent event1)->{
			img2.setImage(new Image("imag/Ok-48.png"));
			Label2.setStyle("-fx-background-color:#47A563");
			img3.setImage(new Image("imag/synching.png"));
			Label1.setText("Here Text2");
			transition3.play();
			
		});
		
		transition3.setOnFinished((ActionEvent event1)->{
			img3.setImage(new Image("imag/Ok-48.png"));
			Label3.setStyle("-fx-background-color:#47A563");
			img4.setImage(new Image("imag/synching.png"));
			Label4.setText("Here Text2");
			transition4.play();
			
		});
		
		
		transition4.setOnFinished((ActionEvent event1)->{
			img4.setImage(new Image("imag/Ok-48.png"));
			Label4.setStyle("-fx-background-color:#47A563");		
		});
		
		
	}
	
	public void dataCleaning(){
		transition1.setOnFinished((ActionEvent event1)->{
			img1.setImage(new Image("imag/Ok-48.png"));
			Label1.setStyle("-fx-background-color:#47A563");
			img2.setImage(new Image("imag/synching.png"));
			Label1.setText("Here Text2");
			transition2.play();
	
		});
	}
}
